name: Vinted Scanner Sara

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scan:
    uses: ./.github/workflows/_vinted-scanner-template.yml
    secrets:
      vinted_config: ${{ secrets.VINTED_CONFIG_SARA }}
